### ISSUE TITLE
Cookie doesn't seem to work

### ISSUE THREAD

**Issue by LotharVM** [JorgeAnzola/environment-protection#2]
Hi,

First of all, great package! I'm experiencing an issue though: the cookie doesn't seem to be working. Any chance you can look into this?

Regards,
Lothar

**Comment by martijnvanonz** [comment]
+1

**Comment by JorgeAnzola** [comment]
Ah, nice! Thanks for reporting this! I'll take a look at it.

**Comment by JorgeAnzola** [comment]
Actually not a bug but part of the road map that I totally forgot! Thanks!
